CREATE SEQUENCE SEQ_CONSUMO_ENERGIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TBL_CONSUMO_ENERGIA (
    ID INTEGER DEFAULT SEQ_CONSUMO_ENERGIA.NEXTVAL NOT NULL PRIMARY KEY,
    NOME_EQUIPAMENTO VARCHAR2(100) NOT NULL,
    SETOR VARCHAR2(50) NOT NULL,
    CONSUMO_KWH NUMBER(10,2) NOT NULL,
    DATA_REGISTRO DATE NOT NULL
);